apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    oidc-issuer-url: https://cilogon.org
    oidc-username-claim: email
    oidc-client-id: KubeHQv1
networking:
  podSubnet: 10.244.0.0/16
