apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-example-cfg
  labels:
    app: kubehq
webhooks:
  - name: safe.kubehq.com
    clientConfig:
      service:
        name: kubehq-svc
        namespace: default
        path: "/validate"
        port: 443
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1","v1beta1"]
        resources: ["deployments","services","pods"]
    namespaceSelector:
      matchLabels:
        webhook: enabled
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None