apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-example-cfg
  labels:
    app: KubeHQ
webhooks:
  - name: required-labels.kubehq.com
    clientConfig:
      service:
        name: KubeHQ-svc
        namespace: default
        path: "/validate"
        port: 443
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    namespaceSelector:
      matchLabels:
        webhook: enabled
    admissionReviewVersions: ["v1", "v1beta1"]
    # sideEffects: None